# Site settings
title: Artists Theme
email: artist@gmail.com
description: "Thinker // Designer // YouTuber"

avatar: travitar.jpg

# Build settings

markdown: kramdown
permalink: pretty

highlighter: rouge

port: 4980

sass:
  sass_dir: assets/css
  style: :nested
